menu:
  Home: /
  Archives: /archives

widgets:
# - search
- category
- tag
- twitter

excerpt_link: Read More

twitter:
  username: thiagopnts
  show_replies: false
  tweet_count: 5

facebook: your facebook url
github: thiagopnts
email: email
about: "Something about you here"
photo: /images/moritam_image.jpg

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:
